export type {
  Message,
  UserRole as CommonUserRole,
  User as CommonUser,
  ApiResponse,
  ApiError,
  ResponseMeta,
  MediaFile,
  PaginationParams,
  PaginatedResponse,
  DateRange,
  SortOrder,
  Status,
  BaseEntity,
  AuditableEntity,
  Environment,
  Config,
  ValidationError,
  ValidationResult
} from './common'

export type {
  UUID as DatabaseUUID,
  Timestamp as DatabaseTimestamp,
  JsonValue,
  JsonObject,
  JsonArray,
  DatabaseType,
  QueryParams,
  WhereCondition,
  OrderBy,
  PaginationOptions as DatabasePaginationOptions,
  TransactionCallback,
  DatabaseError,
  DatabaseConnection,
  RedisConnection,
  HealthStatus,
  QueryResult as DatabaseQueryResult,
  DatabaseOperations,
  RedisOperations,
  UserRole as DatabaseUserRole,
  Gender,
  GrowthCategory as DatabaseGrowthCategory,
  AIRole as DatabaseAIRole,
  NotificationType as DatabaseNotificationType,
  RecommendationType as DatabaseRecommendationType,
  UploadType,
  User as DatabaseUser,
  CreateUser,
  UpdateUser,
  Child,
  CreateChild,
  UpdateChild,
  GrowthRecord as DatabaseGrowthRecord,
  CreateGrowthRecord,
  UpdateGrowthRecord,
  AIConversation,
  CreateAIConversation,
  AIRoleConfig as DatabaseAIRoleConfig,
  CreateAIRole,
  UpdateAIRole,
  Notification as DatabaseNotification,
  CreateNotification,
  UpdateNotification,
  Recommendation as DatabaseRecommendation,
  CreateRecommendation,
  SystemConfig,
  CreateSystemConfig,
  UpdateSystemConfig,
  FileUpload,
  CreateFileUpload,
  UserSession,
  CreateUserSession,
  AuditLog,
  CreateAuditLog,
  UserStats,
  ChildStats,
  DailyStats,
  Migration,
  MigrationStatus,
  QueryBuilder,
  Repository,
  CacheKey,
  CacheValue,
  CacheOptions,
  DatabaseConfig,
  ConnectionPool,
  DatabaseMetrics,
  QueryLog,
  DatabaseLogger,
  TransactionOptions,
  Savepoint,
  Transaction,
  IndexType,
  IndexDefinition,
  ForeignKeyAction,
  ForeignKeyDefinition,
  TriggerTiming,
  TriggerEvent,
  TriggerDefinition,
  ColumnDefinition,
  TableDefinition,
  SchemaDiff,
  DataType,
  ColumnConstraint,
  TableConstraint,
  DatabaseSchema
} from './database'

export type {
  MetricType,
  AggregationType,
  TimeGranularity,
  ChartType,
  TrendDirection,
  ComparisonType,
  AlertSeverity,
  ReportFormat,
  ExportFrequency,
  DataSource,
  Metric,
  MetricValue,
  MetricSeries,
  Dimension,
  Filter,
  QueryOptions,
  QueryResult as AnalyticsQueryResult,
  ChartConfig,
  Dashboard,
  DashboardLayout,
  Widget,
  MetricConfig,
  TableConfig,
  TextConfig,
  Report,
  Schedule,
  Alert,
  AlertCondition,
  NotificationChannel,
  AlertTrigger,
  TrendAnalysis,
  AnomalyDetection,
  Forecast,
  CohortAnalysis,
  FunnelAnalysis,
  Segment,
  HeatmapData,
  SankeyData,
  TreemapData,
  HistogramData,
  ScatterData,
  PerformanceMetrics,
  UserBehaviorMetrics,
  BusinessMetrics,
  GrowthMetrics,
  AssessmentMetrics,
  AnalyticsEvent,
  EventAggregation,
  RealtimeMetric,
  RealtimeDashboard,
  DataQualityReport,
  AnalyticsExport,
  AnalyticsConfig,
  ComparisonResult,
  Insight,
  AnalyticsQuery
} from './analytics'

export type {
  InteractionType,
  InteractionMood,
  InteractionSentiment,
  InteractionRecord,
  InteractionAnalysis,
  InteractionStats,
  InteractionFilter,
  InteractionCreateInput,
  InteractionUpdateInput,
  AIRole as InteractionAIRole,
  AIRoleConfig as InteractionAIRoleConfig,
  ConversationMessage,
  ConversationSession,
  ConversationStats,
  ConversationFilter,
  ConversationCreateInput,
  ConversationHistoryInput,
  EmotionType,
  EmotionAnalysis,
  EmotionTrend,
  EmotionStats,
  CommentType,
  Comment,
  CommentWithUser,
  CommentCreateInput,
  CommentUpdateInput,
  FeedbackType,
  Feedback,
  FeedbackCreateInput,
  FeedbackStats,
  NotificationType as InteractionNotificationType,
  Notification as InteractionNotification,
  NotificationCreateInput as InteractionNotificationCreateInput,
  NotificationStats,
  RatingTargetType,
  Rating,
  RatingCreateInput,
  RatingStats,
  ReactionType,
  Reaction,
  ReactionStats,
  InteractionInsight,
  InteractionDashboard,
  InteractionSearchQuery,
  InteractionSearchResult
} from './interaction'

export type {
  GrowthCategory,
  GrowthStageId,
  DevelopmentDimensionId,
  GrowthRecord,
  GrowthRecordWithAnalysis,
  GrowthRecordAnalysis,
  GrowthRecordStats,
  GrowthRecordFilter,
  GrowthRecordCreateInput,
  GrowthRecordUpdateInput,
  DevelopmentDimension,
  AgeStageConfig,
  Age,
  Milestone,
  MilestoneCreateInput,
  MilestoneUpdateInput,
  MilestoneStats,
  Assessment,
  DimensionScore,
  AssessmentCreateInput,
  AssessmentUpdateInput,
  AssessmentTrend,
  AssessmentStats,
  RecommendationType,
  Recommendation,
  RecommendationCreateInput,
  RecommendationStats,
  GrowthTimeline,
  GrowthSummary,
  GrowthInsight,
  GrowthDashboard,
  GrowthReport,
  GrowthReportChart,
  GrowthGoal,
  GrowthGoalCreateInput,
  GrowthGoalUpdateInput,
  GrowthGoalStats,
  GrowthComparison
} from './growth'

export type {
  ChatMessage,
  ChatSession,
  ChatRole,
  ChatEmotion,
  ChatContext,
  ChatOptions,
  ChatStreamOptions,
  ChatResponse,
  ChatStreamResponse,
  ChatError,
  ChatHistory,
  ChatStats,
  ChatFilter,
  ChatCreateInput,
  ChatUpdateInput
} from './ai'

export type {
  Schedule,
  ScheduleItem,
  ScheduleType,
  ScheduleStatus,
  ScheduleFilter,
  ScheduleCreateInput,
  ScheduleUpdateInput,
  ScheduleStats,
  ScheduleConflict,
  ScheduleReminder
} from './schedule'
